[package]
name = "pig"
version = "0.1.1"
edition = "2021"

[dependencies]
bevy = "0.14.1"
bevy_egui = "0.29.0"
my_library = { package = "my_library", path = "../my_library", features = [ "locking" ] }
